services:
  db:
    image: postgres:16.2-alpine
    container_name: zero_next_db
    environment:
      POSTGRES_DB: zero_next
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    command: |
      postgres
      -c wal_level=logical
      -c max_wal_senders=10
      -c max_replication_slots=5
      -c hot_standby=on
      -c hot_standby_feedback=on
    volumes:
      - data:/var/lib/postgresql/data
      - ./seed-data:/docker-entrypoint-initdb.d
volumes:
  data:
